import gemini from "../config/gemini.js";
import { Emailexecutor } from "./executor.js"


export async function Emailvalidator(Executorresponce){

    const Validatorresponse=await gemini.interactions.create({
        model: "gemini-3.7-flash",

        input: `
            Here is the final email generated by the Executor:

            ${Executorresponce}

            Validate this email.

            If the email has any problems, return:
            NEEDS_CHANGES

            Then explain what needs to be fixed.

            If the email is good, return:
            APPROVED

            Do not rewrite the email.
            
        `
    })

    console.log(Validatorresponse.output_text)

    if (Validatorresponse.output_text.includes("NEEDS_CHANGES")) {

    const executor = await Emailexecutor(`
        Original email:
        ${Executorresponce}

        Validator feedback:
        ${Validatorresponse.output_text}
    `);

        return executor;

    } else {
        return Executorresponce;
    }

}